from selenium.webdriver.common.by import By

class BasePageLocators:
    LOGIN_LINK = (By.CSS_SELECTOR, '.sm_login_item .enter')
    SEARCH_FIELD = (By.CSS_SELECTOR, '#search input:nth-child(2)')
    LOGO = (By.CSS_SELECTOR, '.logo_w_img a')
    PHONE1 = (By.CSS_SELECTOR, '.hm_conts [href="tel:+74951085372"]')
    PHONE2 = (By.CSS_SELECTOR, '.hm_conts [href="tel:+78007004094"]')
    PHONE3 = (By.CSS_SELECTOR, '.hm_conts [href="tel:+74951085325"]')
    PHONE4 = (By.CSS_SELECTOR, '.hm_conts [href="tel:+74954813842"]')
    CALL_BACK = (By.CSS_SELECTOR, '.callb_open')
    BASKET_ICON = (By.CSS_SELECTOR, '#short_basket a')
    BASKET_COUNT = (By.CSS_SELECTOR, '.bask_count')
    BASKET_DELAY = (By.CSS_SELECTOR, '#short_basket_delay a')
    SEND_MESSAGE = (By.CSS_SELECTOR, '.hoverl_acc8')
    GREEN_ASK_QUESTION = (By.CLASS_NAME, '_noAd_b3ae')
    GREEN_ASK_QUESTION_BTN = (By.CLASS_NAME, 'hoverl_fac0')
    MESSAGE_FORM = (By.ID, 'jcont')
    MESSAGE_FORM_TITLE = (By.CLASS_NAME, 'agentName_e60f')
    CLOSE_MESSAGE_FORM = (By.CLASS_NAME, 'closeIcon_c147')
    TELEGRAM_LINK = (By.CSS_SELECTOR, '[href="https://t.me/PodvorjeBot"] .title_f567')
    VK_LINK = (By.CSS_SELECTOR, '[href="https://vk.com/im?sel=-49882277"] .title_f567')
    WHATSAPP_LINK = (By.CSS_SELECTOR, '[href="https://wa.me/74951085372"] .title_f567')
    EASY_MESSAGE_LINK = (By.CSS_SELECTOR, '.hoverl_fac0 jdiv jdiv jdiv jdiv jdiv jdiv .title_f567')
    CLOSE_MESSAGE = (By.CSS_SELECTOR, '.closeIcon_ab78')
    MAIN_MENU_BOARD = (By.CSS_SELECTOR, '.topmenu')
    BLOCK_CATEGORIES = (By.CSS_SELECTOR, '._loaded .kids_topmenu')
    ALL_CATEGORIES = (By.CSS_SELECTOR, '._loaded [href="/retail/catalogue/index.html"]')
    CATALOG = (By.CSS_SELECTOR, '.topmenu .tm_catalog:nth-child(1)')
    DELIVERY = (By.CSS_SELECTOR, '.topmenu [href="/retail/orders.html"]')
    ARTICLES = (By.CSS_SELECTOR, '.topmenu [data-catalog="arts"]')
    BLOCK_ARTS = (By.CSS_SELECTOR, '.is-arts .kids_topmenu')
    ABOUT_US = (By.CSS_SELECTOR, '.topmenu [href="/retail/about.html"]')
    CONTACTS = (By.CSS_SELECTOR, '.topmenu [href="/contacts.html"]')
    SUBSCRIBE_MESSAGE = (By.CSS_SELECTOR, '.puSubscribe.show')
    SUBSCRIBE_NO = (By.CSS_SELECTOR, '#puSubscribe_no.btn')
    SUBSCRIBE_YES = (By.CSS_SELECTOR, '#puSubscribe_yes.btn')

class BasketPageLocators:
    EMPTY_BASKET = (By.CSS_SELECTOR, '.content .error')
    PRODUCT_NAME_IN_BASKET = (By.CSS_SELECTOR, '.table-basket-row .nu')
    BASKET_PRICE = (By.CSS_SELECTOR, '.table-basket-results strong')
    PRODUCT_AMOUNT_MINUS = (By.CSS_SELECTOR, '._count._less')
    PRODUCT_AMOUNT_PLUS = (By.CSS_SELECTOR, '._count._more')
    PRODUCT_DELETE_BUTTON = (By.CSS_SELECTOR, '._delete.basket-btn svg')
    TOTAL_COUNT_PRODUCT_IN_BASKET = (By.CSS_SELECTOR, '.table-basket-results')

class MainPageLocators:
    LOGIN_PHONE_FIELD = (By.ID, 'login-phone')
    EMAIL_FIELD = (By.CSS_SELECTOR, '.login-step-form [name="login_mail"]')
    SUBMIT_BUTTON = (By.CSS_SELECTOR, '.login-step-bottom-btn .btn')
    # [data-step="mail"] [data-function="checkLogin"]
    LOGIN_MAIL_LINK = (By.CSS_SELECTOR, '[data-target="mail"]')
    LOGIN_PHONE_LINK = (By.CSS_SELECTOR, '[data-target="phone"]')
    STEP_BACK_BUTTON = (By.CSS_SELECTOR, '.login-popup-close')
    AVATAR = (By.CSS_SELECTOR, '.sm_login_login')
    PERSONAL_DATA_BUTTON = (By.XPATH, '//*[@id="nom-tabs"]/ul/li[3]/span')
    INFO_EDIT = (By.CSS_SELECTOR, '[href="?mode=edit_info"]')
    USER_PASSWORD = (By.CSS_SELECTOR, '#password')
    LOGIN_PASSWORD = (By.CSS_SELECTOR, '[data-function="loginPass"]')
    VOJTI_BUTTON = (By.CSS_SELECTOR, '[data-function="checkPass"]')
    SAVE_BUTTON = (By.CSS_SELECTOR, '[name="save"]')
    USER_ACCOUNT = (By.CSS_SELECTOR, '[href="/cabinet/index.html"] .enter ')
    EXIT_ACCOUNT = (By.CSS_SELECTOR, '.ind_more_btn a')
    RECOMMEND_YOU_TITLE = (By.CSS_SELECTOR, '.rr-widget-5d11dd1797a528203018b3be .widgettitle')
    RECOMMEND_YOU_BLOCK = (By.CSS_SELECTOR, '.rr-widget-5d11dd1797a528203018b3be .rr-container')
    SALE_HITS_TITLE = (By.CSS_SELECTOR, '.rr-widget-5d11dd3497a528203018b3c3 .widgettitle')
    SALE_HITS_RIGHT = (By.CSS_SELECTOR, '.rr-widget-5d11dd3497a528203018b3c3 .sla_right')
    SALE_HITS_ELEMENT = (By.CSS_SELECTOR, f'.rr-widget-5d11dd3497a528203018b3c3 .slick-slide:nth-child(1) img')
    PROMO_TITLE = (By.CSS_SELECTOR, '.weeks .title')
    PROMO_RIGHT = (By.CSS_SELECTOR, '.weeks .sla_right')
    PROMO_ELEMENT = (By.CSS_SELECTOR, '.week_item:nth-child(1) .week_img')
    PROMO_BUTTON = (By.CSS_SELECTOR, '.weeks .btn')
    NOVELTIES_TITLE = (By.CSS_SELECTOR, '.new_block .title')
    NOVELTIES_RIGHT = (By.CSS_SELECTOR, '.new_block .sla_right')
    NOVELTIES_ELEMENT = (By.CSS_SELECTOR, '.sl_item:nth-child(1) .ni_img')
    NOVELTIES_BUTTON = (By.CSS_SELECTOR, '.new_block .btn')
    OTZIV_TITLE = (By.CSS_SELECTOR, '.otz .title')
    OTZIV_RIGHT = (By.CSS_SELECTOR, '.otz .sla_right')
    OTZIV_BLOCK = (By.CSS_SELECTOR, '.otz .sl_inner')
    OTZIV_ALL_BUTTON = (By.CSS_SELECTOR, '.otz [href="/reviews.html"]')
    OTZIV_SEND_BUTTON = (By.CSS_SELECTOR, '.otz .is-add .btn')
    NEWS_TITLE = (By.CSS_SELECTOR, '.news_block .title')
    NEWS_ALL_BUTTON = (By.CSS_SELECTOR, '.news_block .btn')
    NEWS_RSS_BUTTON = (By.CSS_SELECTOR, '.news_block .rss_btn')
    NEWS_BLOCK = (By.CSS_SELECTOR, '.news_box')



class LoginPageLocators:
    NAME_FIELD = (By.CSS_SELECTOR, '[name="info_full_fio"]')
    EMAIL_FIELD = (By.CSS_SELECTOR, '[name="reg_email"]')
    CHECKBOX_NEWS = (By.CSS_SELECTOR, '.form-input [data-function="massSubsToggle"]')
    REG_SUBMIT_BUTTON = (By.CSS_SELECTOR, '[id="reg-submit-btn"]')
    MAIN_PHONE_NUMBER = (By.CSS_SELECTOR, '[id="info_phone"]')
    SECOND_PHONE_NUMBER = (By.CSS_SELECTOR, '[id="info_phone_cell"]')
    JURA_CHECKBOX = (By.CSS_SELECTOR, '[id="info_is_org"]')
    ZIP_CHECKBOX = (By.CSS_SELECTOR, '[id="sub_5"]')

class ProductPageLocators:
    PRODUCT_NAME = (By.CSS_SELECTOR, '.nom_title_box')
    PRODUCT_PRICE = (By.CSS_SELECTOR, '.sib_act_price')
    PRODUCT_PHOTO = (By.CSS_SELECTOR, '.nom-image-new')
    BASKET_BUTTON = (By.CSS_SELECTOR, '.sib-count-btn')
    PRODUCT_INFO_TABLE = (By.CSS_SELECTOR, '.nom-tabs__btns')
    PRODUCT_INFO_BLOCK = (By.CSS_SELECTOR, '.sib_behs')

